version: '3.1'
services:
    nginx:
        image: nginx:latest
        ports:
            - "3000:8000"
        volumes:
            - ./testproject/provisioning/nginx.conf:/etc/nginx/conf.d/default.conf:cached
            - ./testproject:/application:cached
        depends_on:
            - blog-server
    blog-server:
        build: ./testproject/provisioning
        image: laravel-blog
        depends_on:
            - phpmyadmin-laravel
        volumes:
            - ./testproject:/application:cached
    phpmyadmin-laravel:
        image: phpmyadmin/phpmyadmin:latest
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: "111111"
            MYSQL_DATABASE: "shop_db"
            MYSQL_USER: "shop"
            MYSQL_PASSWORD: "123456"